// --- BASE DE DONNÉES ÉTENDUE : 100 VERBES ---
const verbs = [
    { fr: "parler", es: "hablar", icon: "🗣️", group: "er", aux: "avoir", pp: "parlé", comp: "français" },
    { fr: "manger", es: "comer", icon: "🍝", group: "er", aux: "avoir", pp: "mangé", comp: "une pizza" },
    { fr: "regarder", es: "mirar", icon: "👀", group: "er", aux: "avoir", pp: "regardé", comp: "un film" },
    { fr: "écouter", es: "escuchar", icon: "🎧", group: "er", aux: "avoir", pp: "écouté", comp: "de la musique" },
    { fr: "travailler", es: "trabajar", icon: "💼", group: "er", aux: "avoir", pp: "travaillé", comp: "au bureau" },
    { fr: "étudier", es: "estudiar", icon: "📚", group: "er", aux: "avoir", pp: "étudié", comp: "la leçon" },
    { fr: "chanter", es: "cantar", icon: "🎤", group: "er", aux: "avoir", pp: "chanté", comp: "une belle chanson" },
    { fr: "danser", es: "bailar", icon: "💃", group: "er", aux: "avoir", pp: "dansé", comp: "toute la nuit" },
    { fr: "acheter", es: "comprar", icon: "🛍️", group: "er", aux: "avoir", pp: "acheté", irreg: true, comp: "du pain" },
    { fr: "payer", es: "pagar", icon: "💳", group: "er", aux: "avoir", pp: "payé", irreg: true, comp: "l'addition" },
    { fr: "chercher", es: "buscar", icon: "🔍", group: "er", aux: "avoir", pp: "cherché", comp: "les clés" },
    { fr: "trouver", es: "encontrar", icon: "🎯", group: "er", aux: "avoir", pp: "trouvé", comp: "la solution" },
    { fr: "penser", es: "pensar", icon: "🤔", group: "er", aux: "avoir", pp: "pensé", comp: "à l'avenir" },
    { fr: "appeler", es: "llamar", icon: "📱", group: "er", aux: "avoir", pp: "appelé", irreg: true, comp: "un ami" },
    { fr: "aimer", es: "amar", icon: "❤️", group: "er", aux: "avoir", pp: "aimé", comp: "le chocolat" },
    { fr: "marcher", es: "caminar", icon: "🚶‍♂️", group: "er", aux: "avoir", pp: "marché", comp: "dans le parc" },
    { fr: "cuisiner", es: "cocinar", icon: "🍳", group: "er", aux: "avoir", pp: "cuisiné", comp: "un bon repas" },
    { fr: "voyager", es: "viajar", icon: "✈️", group: "er", aux: "avoir", pp: "voyagé", comp: "en train" },
    { fr: "arriver", es: "llegar", icon: "🏁", group: "er", aux: "etre", pp: "arrivé", comp: "en retard" },
    { fr: "jouer", es: "jugar", icon: "⚽", group: "er", aux: "avoir", pp: "joué", comp: "au football" },

    { fr: "finir", es: "terminar", icon: "✅", group: "ir", aux: "avoir", pp: "fini", comp: "les devoirs" },
    { fr: "choisir", es: "elegir", icon: "👉", group: "ir", aux: "avoir", pp: "choisi", comp: "un livre" },
    { fr: "réussir", es: "lograr", icon: "🎓", group: "ir", aux: "avoir", pp: "réussi", comp: "l'examen" },
    { fr: "grandir", es: "crecer", icon: "🌱", group: "ir", aux: "avoir", pp: "grandi", comp: "très vite" },
    { fr: "dormir", es: "dormir", icon: "🛌", group: "ir3", aux: "avoir", pp: "dormi", irreg: true, comp: "profondément" },
    { fr: "partir", es: "irse", icon: "🚂", group: "ir3", aux: "etre", pp: "parti", irreg: true, comp: "en vacances" },
    { fr: "sortir", es: "salir", icon: "🚪", group: "ir3", aux: "etre", pp: "sorti", irreg: true, comp: "avec des amis" },
    { fr: "sentir", es: "sentir", icon: "👃", group: "ir3", aux: "avoir", pp: "senti", irreg: true, comp: "les fleurs" },
    { fr: "ouvrir", es: "abrir", icon: "🔓", group: "ir3", aux: "avoir", pp: "ouvert", irreg: true, comp: "la porte" },
    { fr: "offrir", es: "ofrecer", icon: "🎁", group: "ir3", aux: "avoir", pp: "offert", irreg: true, comp: "un cadeau" },

    { fr: "vendre", es: "vender", icon: "🏪", group: "re", aux: "avoir", pp: "vendu", comp: "la voiture" },
    { fr: "attendre", es: "esperar", icon: "⏳", group: "re", aux: "avoir", pp: "attendu", comp: "le bus" },
    { fr: "répondre", es: "responder", icon: "💬", group: "re", aux: "avoir", pp: "répondu", comp: "au teléfono" },
    { fr: "entendre", es: "escuchar", icon: "👂", group: "re", aux: "avoir", pp: "entendu", comp: "un bruit" },
    { fr: "perdre", es: "perder", icon: "📉", group: "re", aux: "avoir", pp: "perdu", comp: "le match" },
    { fr: "lire", es: "leer", icon: "📖", group: "re", aux: "avoir", pp: "lu", irreg: true, comp: "un roman" },
    { fr: "écrire", es: "escribir", icon: "✍️", group: "re", aux: "avoir", pp: "écrit", irreg: true, comp: "une lettre" },
    { fr: "prendre", es: "tomar", icon: "🖐️", group: "re", aux: "avoir", pp: "pris", irreg: true, comp: "le métro" },
    { fr: "mettre", es: "poner", icon: "📥", group: "re", aux: "avoir", pp: "mis", irreg: true, comp: "le manteau" },
    { fr: "comprendre", es: "entender", icon: "💡", group: "re", aux: "avoir", pp: "compris", irreg: true, comp: "la question" },
    { fr: "connaître", es: "conocer", icon: "🤝", group: "re", aux: "avoir", pp: "connu", irreg: true, comp: "la vérité" },
    { fr: "croire", es: "creer", icon: "🙏", group: "re", aux: "avoir", pp: "cru", irreg: true, comp: "aux fantômes" },
    { fr: "voir", es: "ver", icon: "👁️", group: "oir", aux: "avoir", pp: "vu", irreg: true, comp: "un oiseau" },
    { fr: "pouvoir", es: "poder", icon: "💪", group: "oir", aux: "avoir", pp: "pu", irreg: true, comp: "le faire" },
    { fr: "vouloir", es: "querer", icon: "🎯", group: "oir", aux: "avoir", pp: "voulu", irreg: true, comp: "un café" },
    { fr: "devoir", es: "deber", icon: "⚠️", group: "oir", aux: "avoir", pp: "dû", irreg: true, comp: "partir tôt" },
    { fr: "être", es: "ser/estar", icon: "🌟", aux: "avoir", pp: "été", irreg: true, comp: "heureux" },
    { fr: "avoir", es: "tener/haber", icon: "🤲", aux: "avoir", pp: "eu", irreg: true, comp: "un chat" },
    { fr: "aller", es: "ir", icon: "🗺️", aux: "etre", pp: "allé", irreg: true, comp: "au cinéma" },
    { fr: "faire", es: "hacer", icon: "🛠️", aux: "avoir", pp: "fait", irreg: true, comp: "du sport" },

    { fr: "boire", es: "beber", icon: "🥛", group: "re", aux: "avoir", pp: "bu", irreg: true, comp: "de l'eau" },
    { fr: "savoir", es: "saber", icon: "🧠", group: "oir", aux: "avoir", pp: "su", irreg: true, comp: "la respuesta" },
    { fr: "venir", es: "venir", icon: "🚶", group: "ir3", aux: "etre", pp: "venu", irreg: true, comp: "ici" },
    { fr: "courir", es: "correr", icon: "🏃", group: "ir3", aux: "avoir", pp: "couru", irreg: true, comp: "un marathon" },
    { fr: "rire", es: "reír", icon: "😂", group: "re", aux: "avoir", pp: "ri", irreg: true, comp: "beaucoup" },
    { fr: "conduire", es: "conducir", icon: "🚗", group: "re", aux: "avoir", pp: "conduit", irreg: true, comp: "une voiture" },
    { fr: "recevoir", es: "recibir", icon: "📬", group: "oir", aux: "avoir", pp: "reçu", irreg: true, comp: "un colis" },
    { fr: "descendre", es: "bajar", icon: "⬇️", group: "re", aux: "etre", pp: "descendu", comp: "l'escalier" },
    { fr: "répéter", es: "repetir", icon: "🔁", group: "er", aux: "avoir", pp: "répété", irreg: true, comp: "la phrase" },
    { fr: "nettoyer", es: "limpiar", icon: "🧹", group: "er", aux: "avoir", pp: "nettoyé", irreg: true, comp: "la maison" },

    { fr: "se lever", root: "lever", es: "levantarse", icon: "🛏️", group: "er", aux: "etre", pp: "levé", pron: true, comp: "tôt" },
    { fr: "se laver", root: "laver", es: "lavarse", icon: "🧼", group: "er", aux: "etre", pp: "lavé", pron: true, comp: "les mains" },
    { fr: "se réveiller", root: "réveiller", es: "despertarse", icon: "⏰", group: "er", aux: "etre", pp: "réveillé", pron: true, comp: "à 7h" },
    { fr: "se coucher", root: "coucher", es: "acostarse", icon: "🛌", group: "er", aux: "etre", pp: "couché", pron: true, comp: "tard" },
    { fr: "s'habiller", root: "habiller", es: "vestirse", icon: "👕", group: "er", aux: "etre", pp: "habillé", pron: true, comp: "vite" },
    { fr: "se promener", root: "promener", es: "pasear", icon: "🚶", group: "er", aux: "etre", pp: "promené", pron: true, comp: "au parc" },
    { fr: "se dépêcher", root: "dépêcher", es: "darse prisa", icon: "⏱️", group: "er", aux: "etre", pp: "dépêché", pron: true, comp: "pour le train" },
    { fr: "se souvenir", root: "souvenir", es: "acordarse", icon: "💭", group: "ir3", aux: "etre", pp: "souvenu", pron: true, comp: "de tout" },
    { fr: "tomber", es: "caer", icon: "🍂", group: "er", aux: "etre", pp: "tombé", comp: "par terre" },
    { fr: "monter", es: "subir", icon: "🧗", group: "er", aux: "etre", pp: "monté", comp: "l'escalier" },
    { fr: "rester", es: "quedarse", icon: "🏠", group: "er", aux: "etre", pp: "resté", comp: "à la maison" },
    { fr: "rentrer", es: "volver/entrar", icon: "🔙", group: "er", aux: "etre", pp: "rentré", comp: "chez moi" },
    { fr: "retourner", es: "regresar", icon: "🔄", group: "er", aux: "etre", pp: "retourné", comp: "en France" },
    { fr: "oublier", es: "olvidar", icon: "🧠", group: "er", aux: "avoir", pp: "oublié", comp: "son mot de passe" },
    { fr: "espérer", es: "esperar", icon: "🤞", group: "er", aux: "avoir", pp: "espéré", irreg: true, comp: "un miracle" },
    { fr: "envoyer", es: "enviar", icon: "📧", group: "er", aux: "avoir", pp: "envoyé", irreg: true, comp: "un message" },
    { fr: "essayer", es: "intentar", icon: "🎯", group: "er", aux: "avoir", pp: "essayé", irreg: true, comp: "de comprendre" },
    { fr: "vivre", es: "vivir", icon: "❤️", group: "re", aux: "avoir", pp: "vécu", irreg: true, comp: "en paix" },
    { fr: "mourir", es: "morir", icon: "🥀", group: "ir3", aux: "etre", pp: "mort", irreg: true, comp: "de rire" },
    { fr: "naître", es: "nacer", icon: "👶", group: "re", aux: "etre", pp: "né", irreg: true, comp: "en 2000" },

    { fr: "accepter", es: "aceptar", icon: "✅", group: "er", aux: "avoir", pp: "accepté", comp: "l'offre" },
    { fr: "aider", es: "ayudar", icon: "🤝", group: "er", aux: "avoir", pp: "aidé", comp: "un ami" },
    { fr: "annuler", es: "cancelar", icon: "❌", group: "er", aux: "avoir", pp: "annulé", comp: "le vol" },
    { fr: "apporter", es: "traer", icon: "📦", group: "er", aux: "avoir", pp: "apporté", comp: "un dessert" },
    { fr: "cacher", es: "esconder", icon: "🙈", group: "er", aux: "avoir", pp: "caché", comp: "le trésor" },
    { fr: "changer", es: "cambiar", icon: "🔄", group: "er", aux: "avoir", pp: "changé", comp: "d'avis" },
    { fr: "commencer", es: "comenzar", icon: "▶️", group: "er", aux: "avoir", pp: "commencé", comp: "le travail" },
    { fr: "continuer", es: "continuar", icon: "⏩", group: "er", aux: "avoir", pp: "continué", comp: "à marcher" },
    { fr: "couper", es: "cortar", icon: "✂️", group: "er", aux: "avoir", pp: "coupé", comp: "le papier" },
    { fr: "créer", es: "crear", icon: "🎨", group: "er", aux: "avoir", pp: "créé", comp: "un projet" },
    { fr: "demander", es: "preguntar", icon: "🙋", group: "er", aux: "avoir", pp: "demandé", comp: "de l'aide" },
    { fr: "donner", es: "dar", icon: "🎁", group: "er", aux: "avoir", pp: "donné", comp: "un conseil" },
    { fr: "entrer", es: "entrar", icon: "🚪", group: "er", aux: "etre", pp: "entré", comp: "dans la pièce" },
    { fr: "expliquer", es: "explicar", icon: "🏫", group: "er", aux: "avoir", pp: "expliqué", comp: "la leçon" },
    { fr: "fermer", es: "cerrar", icon: "🔒", group: "er", aux: "avoir", pp: "fermé", comp: "la fenêtre" },
    { fr: "gagner", es: "ganar", icon: "🏆", group: "er", aux: "avoir", pp: "gagné", comp: "le concours" },
    { fr: "montrer", es: "mostrar", icon: "🖼️", group: "er", aux: "avoir", pp: "montré", comp: "la photo" },
    { fr: "pleurer", es: "llorar", icon: "😢", group: "er", aux: "avoir", pp: "pleuré", comp: "de joie" },
    { fr: "rencontrer", es: "encontrar(se)", icon: "🫂", group: "er", aux: "avoir", pp: "rencontré", comp: "quelqu'un" },
    { fr: "utiliser", es: "utilizar", icon: "🛠️", group: "er", aux: "avoir", pp: "utilisé", comp: "un outil" }
];
